### ISSUE TITLE
VErsion Java

### ISSUE THREAD

**Issue by Pascal66** [consometers/data-connect#3]
Elle est indiquée partout mais introuvable ici ?

**Comment by cyril-L** [comment]
Bonjour Pascal,

Effectivement on ne parle pas de Java dans ce dépôt puisque que nous ne l’utilisons pas.
Peux-tu précisier ta question ?

**Comment by Pascal66** [comment]
Bonjour, merci de ta réponse.

J’ai résolu mon problème, même si mon api java fonctionnant parfaitement à j+1, ce ne m’est d’aucune utilité.
Comme je n’ai pas accès au compteur (éloigné de 10m)
Je ne mettrais pas un module Wifi à 90€ dans la rue.

Je vais donc me passer des infos du Linky pour le moment.


De : Cyril Lugan
Envoyé le :jeudi 28 janvier 2021 09:47
À : consometers/data-connect
Cc : Priveyes; Author
Objet :Re: [consometers/data-connect] VErsion Java (#3)

Bonjour Pascal,
Effectivement on ne parle pas de Java dans ce dépôt puisque que nous ne l’utilisons pas.
Peux-tu précisier ta question ?
